const nodemailer = require('nodemailer');
const db = require('../database/db');
const { generateDailyDigest } = require('../ai/geminiService');

async function sendDailyDigest(options = {}) {
    const { dryRun = false } = options;
    console.log("Generating daily digest...");
    
    const events = db.prepare(`
        SELECT * FROM events 
        WHERE discoveredAt >= datetime('now', '-1 day') 
        ORDER BY importanceScore DESC LIMIT 15
    `).all();

    if (events.length === 0) {
        console.log("No events to send in digest.");
        return { dryRun, sent: false, reason: 'No events' };
    }

    const aiSummary = await generateDailyDigest(events);

    let html = `
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; color: #333;">
            <h1 style="border-bottom: 2px solid #000; padding-bottom: 10px;">AI Intelligence Briefing</h1>
            <p style="color: #666; font-size: 14px;">${new Date().toLocaleDateString()}</p>
            
            <p>Good morning.</p>
            <p>Here are today's most important AI developments.</p>
            
            <div style="background: #f4f4f4; padding: 15px; border-radius: 5px; margin-bottom: 30px;">
                <h3 style="margin-top: 0;">Executive Overview</h3>
                <p style="margin-bottom: 0;">${aiSummary.replace(/\n/g, '<br/>')}</p>
            </div>

            <h2>TOP DEVELOPMENTS</h2>
    `;

    events.forEach((event, index) => {
        let keyPointsHtml = '';
        try {
            const points = JSON.parse(event.keyPoints || '[]');
            if (points.length) {
                keyPointsHtml = `<ul>${points.map(p => `<li>${p}</li>`).join('')}</ul>`;
            }
        } catch(e) {}

        const articles = db.prepare('SELECT sources.sourceName, articles.url FROM articles JOIN sources ON articles.sourceId = sources.id WHERE articles.eventId = ?').all(event.id);
        const sourceLinks = articles.map(a => `<a href="${a.url}">${a.sourceName}</a>`).join(', ');

        html += `
            <div style="margin-bottom: 25px; border-left: 4px solid #3b82f6; padding-left: 15px;">
                <h3 style="margin: 0 0 10px 0;">${index + 1}. ${event.title}</h3>
                <p><strong>What happened:</strong> ${event.summary}</p>
                <p><strong>Why it matters:</strong> ${event.whyItMatters}</p>
                ${keyPointsHtml}
                <p style="font-size: 12px; color: #666;">
                    <strong>Confidence:</strong> ${event.confidenceLabel} | 
                    <strong>Sources:</strong> ${sourceLinks}
                </p>
            </div>
        `;
    });

    html += `
        <p style="font-size: 12px; color: #999; border-top: 1px solid #eee; padding-top: 20px; margin-top: 40px;">
            This briefing was automatically generated by AI News Aggregator.
        </p>
        </div>
    `;

    try {
        const transporter = nodemailer.createTransport({
            host: process.env.SMTP_HOST,
            port: parseInt(process.env.SMTP_PORT, 10),
            secure: process.env.SMTP_SECURE === 'true',
            auth: {
                user: process.env.SMTP_USER,
                pass: process.env.SMTP_PASSWORD
            }
        });

        await transporter.sendMail({
            from: process.env.EMAIL_FROM,
            to: process.env.EMAIL_TO,
            subject: `AI Intelligence Briefing — ${new Date().toLocaleDateString()}`,
            html: html
        });

        db.prepare("INSERT INTO daily_digests (content, status) VALUES (?, ?)").run(html, 'success');
        console.log("Daily digest sent successfully.");
    } catch (error) {
        console.error("Failed to send daily digest:", error);
        db.prepare("INSERT INTO daily_digests (content, status) VALUES (?, ?)").run(error.message, 'error');
        db.prepare("INSERT INTO system_logs (level, module, message) VALUES (?, ?, ?)").run('error', 'digestService', `Error sending digest: ${error.message}`);
    }
}

module.exports = {
    sendDailyDigest
};
